In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('coffeeshop_dataset.csv')
df.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [3]:
#dataset information and statistical summary 
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   object
 1   datetime     3636 non-null   object
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

,date,datetime,cash_type,card,money,coffee_name
count,3636,3636,3636,3547,3636.000000,3636
unique,381,3636,2,1316,NaN,8
top,2024-10-11,2025-03-23 18:11:38.635,card,ANON-0000-0000-0012,NaN,Americano with Milk
freq,26,1,3547,129,NaN,824
mean,NaN,NaN,NaN,NaN,31.746859,NaN
std,NaN,NaN,NaN,NaN,4.919926,NaN
min,NaN,NaN,NaN,NaN,18.120000,NaN
25%,NaN,NaN,NaN,NaN,27.920000,NaN
50%,NaN,NaN,NaN,NaN,32.820000,NaN
75%,NaN,NaN,NaN,NaN,35.760000,NaN
max,NaN,NaN,NaN,NaN,40.000000,NaN

In [4]:
#unique value exploration
payment_type = df['cash_type'].unique()
list_menu = df['coffee_name'].unique()
print("list cash:", payment_type)
print("list_name:", list_menu)

list cash: ['card' 'cash']
list_name: ['Latte' 'Hot Chocolate' 'Americano' 'Americano with Milk' 'Cocoa'
 'Cortado' 'Espresso' 'Cappuccino']

In [5]:
#check duplicate
total_duplicate = df.duplicated().sum()
print(total_duplicate)

0

In [6]:
#delete column date and check detail information from my dataset
df = df.drop(columns=['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     3636 non-null   object
 1   cash_type    3636 non-null   object
 2   card         3547 non-null   object
 3   money        3636 non-null   float64
 4   coffee_name  3636 non-null   object
dtypes: float64(1), object(4)
memory usage: 142.2+ KB

In [7]:
#change format column datetime & rename column
df['datetime'] = pd.to_datetime(df['datetime'])
df.rename(columns={'datetime': 'date'}, inplace=True)
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   datetime64[ns]
 1   cash_type    3636 non-null   object
 2   card         3547 non-null   object
 3   money        3636 non-null   float64
 4   coffee_name  3636 non-null   object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 142.2+ KB

,date,cash_type,card,money,coffee_name
0,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte
5,2024-03-01 15:39:47.726,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01 18:39:03.580,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01 19:22:01.762,card,ANON-0000-0000-0008,38.7,Cocoa
9,2024-03-01 19:23:15.887,card,ANON-0000-0000-0008,33.8,Americano with Milk

In [8]:
#rename column money to total_amount and change the capitalization format in the dataset
df.rename(columns={'money': 'total_amount'}, inplace=True)
df[['cash_type','card']] =df[['cash_type', 'card']].apply(lambda x: x.str.title())
df.head(10)

,date,cash_type,card,total_amount,coffee_name
0,2024-03-01 10:15:50.520,Card,Anon-0000-0000-0001,38.7,Latte
1,2024-03-01 12:19:22.539,Card,Anon-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01 12:20:18.089,Card,Anon-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01 13:46:33.006,Card,Anon-0000-0000-0003,28.9,Americano
4,2024-03-01 13:48:14.626,Card,Anon-0000-0000-0004,38.7,Latte
5,2024-03-01 15:39:47.726,Card,Anon-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01 16:19:02.756,Card,Anon-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01 18:39:03.580,Card,Anon-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01 19:22:01.762,Card,Anon-0000-0000-0008,38.7,Cocoa
9,2024-03-01 19:23:15.887,Card,Anon-0000-0000-0008,33.8,Americano with Milk

In [9]:
#checking null value & count total null value
df_null = df[df['card'].isnull()]
print(df.isnull().sum())

date             0
cash_type        0
card            89
total_amount     0
coffee_name      0
dtype: int64

In [10]:
#change null values from card column to 0 because it's count as a real transaction
df['card'] = df['card'].fillna('Cash')
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          3636 non-null   datetime64[ns]
 1   cash_type     3636 non-null   object
 2   card          3636 non-null   object
 3   total_amount  3636 non-null   float64
 4   coffee_name   3636 non-null   object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 142.2+ KB

,date,cash_type,card,total_amount,coffee_name
0,2024-03-01 10:15:50.520,Card,Anon-0000-0000-0001,38.7,Latte
1,2024-03-01 12:19:22.539,Card,Anon-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01 12:20:18.089,Card,Anon-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01 13:46:33.006,Card,Anon-0000-0000-0003,28.9,Americano
4,2024-03-01 13:48:14.626,Card,Anon-0000-0000-0004,38.7,Latte
5,2024-03-01 15:39:47.726,Card,Anon-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01 16:19:02.756,Card,Anon-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01 18:39:03.580,Card,Anon-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01 19:22:01.762,Card,Anon-0000-0000-0008,38.7,Cocoa
9,2024-03-01 19:23:15.887,Card,Anon-0000-0000-0008,33.8,Americano with Milk

In [11]:
#Export data

df.to_csv('coffeeshop_dataset_clean.csv', index=False)
print("Export data success!")

Export data success!